import { expect, test } from '@playwright/test'

test('plays, pauses, scrubs and restarts the shared scene clock', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('./')
  await expect(page.getByText('Synthetic test data', { exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  const clock = page.getByTestId('clock')
  await expect(clock).toContainText('07:05:00')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(clock).not.toContainText('07:05:00')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const paused = await clock.textContent()
  await page.waitForTimeout(350)
  await expect(clock).toHaveText(paused!)
  await page.getByRole('combobox', { name: 'Playback speed' }).selectOption('120')
  const slider = page.getByRole('slider', { name: 'Service time' })
  await slider.focus()
  await slider.press('End')
  await expect(clock).toContainText('09:00:00')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(clock).toContainText('07:00:')
  await slider.focus()
  await slider.press('Home')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await expect(clock).toContainText('07:00:00')
  expect(errors).toEqual([])
})

test('focuses routes and searches source translations without changing station identity', async ({ page }) => {
  await page.goto('./')
  await expect(page.locator('.station-list button')).toHaveCount(7)
  await page.getByRole('button', { name: 'Fictional Loop' }).click()
  await expect(page.locator('.station-list button')).toHaveCount(4)
  await page.getByRole('searchbox', { name: 'Find a station' }).fill('架空北西')
  await expect(page.locator('.station-list button')).toHaveCount(1)
  await page.getByRole('button', { name: 'Fictional Northwest' }).click()
  const detail = page.getByRole('region', { name: 'Selected station' })
  await expect(detail).toContainText('Fictional Northwest')
  await page.getByRole('combobox', { name: 'Station language' }).selectOption('ja')
  await expect(detail).toContainText('架空北西')
  await page.getByRole('searchbox', { name: 'Find a station' }).fill('Northwest')
  await expect(page.locator('.station-list button')).toHaveCount(1)
  await page.getByRole('button', { name: 'Clear station selection' }).click()
  await expect(detail).toHaveCount(0)
  await page.getByRole('searchbox', { name: 'Find a station' }).fill('unknown station')
  await expect(page.getByText('No matching stations.', { exact: false })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Find a station' }).press('Space')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('honors reduced motion and pauses when the preference changes', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('./')
  await expect(page.getByText('Reduced motion is enabled.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeEnabled()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
})

test('retries a failed fixture request and rejects non-synthetic data', async ({ page }) => {
  await page.route('**/data/synthetic-preview.json', (route) => route.fulfill({ status: 503, body: 'unavailable' }))
  await page.goto('./')
  await expect(page.getByRole('alert')).toContainText('Preview data could not be loaded')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeDisabled()
  await page.unroute('**/data/synthetic-preview.json')
  await page.getByRole('button', { name: 'Retry loading' }).click()
  await expect(page.getByTestId('clock')).toContainText('07:05:00')
  await page.route('**/data/synthetic-preview.json', (route) => route.fulfill({ json: { kind: 'operator-feed' } }))
  await page.reload()
  await expect(page.getByRole('alert')).toBeVisible()
})

test('offers useful inspection when WebGL is unavailable', async ({ page }) => {
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext
    HTMLCanvasElement.prototype.getContext = function (type: string, ...args: unknown[]) {
      return type === 'webgl2' ? null : original.call(this, type as '2d', ...args)
    } as typeof original
  })
  await page.goto('./')
  await expect(page.getByText('3D view unavailable')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeDisabled()
  const slider = page.getByRole('slider', { name: 'Service time' })
  await slider.focus()
  await slider.press('End')
  await expect(page.getByTestId('clock')).toContainText('09:00:00')
  await expect(page.locator('.station-list button')).toHaveCount(7)
})

test('keeps controls usable with doubled text size', async ({ page }) => {
  await page.goto('./')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeEnabled()
  await page.addStyleTag({ content: 'html { font-size: 200%; }' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('combobox', { name: 'Playback speed' }).selectOption('120')
  await page.getByRole('searchbox', { name: 'Find a station' }).fill('Midpoint')
  await expect(page.locator('.station-list button')).toHaveCount(1)
})
